//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Id { get; set; }
        public string AuthToken { get; set; }
        public int UserAuthInfoId { get; set; }
        public System.DateTime ExpiredOn { get; set; }
        public string DeviceToken { get; set; }
        public bool IsVerified { get; set; }
        public string DeviceType { get; set; }
    
        public virtual UserAuthInfo UserAuthInfo { get; set; }
    }
}
