//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthInfo
    {
        public UserAuthInfo()
        {
            this.OTPs = new HashSet<OTP>();
            this.Sessions = new HashSet<Session>();
            this.Pets = new HashSet<Pet>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string PasswordHash { get; set; }
    
        public virtual ICollection<OTP> OTPs { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Pet> Pets { get; set; }
    }
}
